[C] allow number, text, and textarea in table cell
lsst-epo/investigations-client pull request #165
Opened 2024-04-15 19:57 UTC by alexgoff

## What this change does ##

Allows standalone text, textarea, and number type questions to be added to a display table

## Notes for reviewers ##

Includes client and API branch.

Include an indication of how detailed a review you want on a 1-10 scale.
- 4

## Testing ##

- Create a mix of text, textarea, number, and table type questions
- Create a display table (within the investigation pages, not as a question)
- Create a row of headers to label the questions
- Create a row and add your previously created questions under "previous question"
    - the order added is the order the questions will be displayed

See that:
- The results of the questions are rendered in a read-only format with previously entered answers retrieved
- A mix of questions including mixing standalone questions and table type questions co-exist on single row

## Checklist ##

If any of the following are true, please check them off
- [ ] This is a breaking change: changes in page data (`/src/data/pages/PAGE.json`) or scientific data (anything in `/static/`) and I will notify Product Marketing when it is in prod and user visible.
- [ ] This change impacts several investigations (e.g. the change affects reuseed styles, widgets, pages, QAs, utility methods, etc.)
- [x] This change is isolated to a specific page or Component (i.e. it's a one-off)
- [ ] I don't know what this change does

## Screenshots (optional) ##
### Before:
### After:

2024-04-15 20:09 UTC, alexgoff commented on components/layout/Table/helpers.tsx
> +    if (readOnly) {
build cells into `readOnly` out here instead of having the question cells figure out if they are read-only or not

2024-04-15 20:09 UTC, alexgoff commented on components/layout/Table/helpers.tsx
> +export const buildPreviousQuestions = (questions = []) => {
new helper that builds all the different types of previous questions that could be in a row. Mostly this is used for differentiating tabular questions, which will contain sub-questions, from "primitive" question types

2024-04-15 20:09 UTC, alexgoff commented on components/questions/TabularQuestion/ReadOnly/index.tsx
> +const ReadOnlyCell: FunctionComponent<ReadOnlyCellProps> = ({
move the work of figuring out how to display the answer in a read-only state out to the readonly cell

2024-04-18 18:33 UTC, blnkt requested changes
In a static table, when the row header is used in combination with (i.e. in the same row as) previous questions cells, the row header is amended to the row instead of prepended to the row (i.e. is always last in the row instead of always first). See screenshots: in the frontend screenshot, the first row after the table header is what corresponds to the CMS screenshot


![Screen Shot 2024-04-18 at 11 31 01 AM](https://github.com/lsst-epo/investigations-client/assets/8166060/5c8abb7b-6b10-46e1-9e94-cf844ad20b9a)
![Screen Shot 2024-04-18 at 11 30 02 AM](https://github.com/lsst-epo/investigations-client/assets/8166060/8c7613f8-80c9-42d1-b3d2-994fee4ca228)

2024-04-18 22:09 UTC, merged