[F] Finish implementing Facebook SSO
lsst-epo/investigations-client pull request #36
Opened 2023-08-07 18:52 UTC by dananjohnson

## What this change does ##

This PR adds the missing dialog which sends a mutation to the API to register and authenticate a user signing in with their Facebook account.

## Notes for reviewers ##

Note that this feature won't fully work if the Facebook app isn't successfully authenticating you and redirecting you back to `localhost`. This was the case for me, but after going back and forth with Blake it seems like the issue is with my local or with me not being an admin on the Facebook app. He was able to go through this process just fine. See the thread in Slack, near the bottom, for the discussion.

- 5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"

## Testing ##

Make sure to update your API repo to use `http://localhost:3000/?facebook_sso=true` for the Facebook redirect URL.

## Checklist ##

If any of the following are true, please check them off
- [ ] This is a breaking change: changes in page data (`/src/data/pages/PAGE.json`) or scientific data (anything in `/static/`) and I will notify Product Marketing when it is in prod and user visible.
- [ ] This change impacts several investigations (e.g. the change affects reuseed styles, widgets, pages, QAs, utility methods, etc.)
- [X] This change is isolated to a specific page or Component (i.e. it's a one-off)
- [ ] I don't know what this change does

2023-08-09 21:47 UTC, alexgoff requested changes
just one small note to check that an i18n string has a matching context, otherwise looks ok

2023-08-09 21:47 UTC, alexgoff commented on components/auth/dialogs/SignInFacebook/SignInFacebook.tsx
> +        return t("facebook_sso.success_message", { context: pendingGroup });
there's a context here for "pendingGroup", but I don't see a matching key in the translation strings, is it missing or is this context unused?

2023-08-09 22:07 UTC, dananjohnson commented on public/localeStrings/en/translation.json
> +    "success_message_educator": "Your account has been activated, but it will need to be approved by an administrator before you can access educator content. You will receive an email when you have b
@alexgoff here's the key that uses the `pendingGroup` context, falling back to just `success_message` as the default.

2023-08-09 22:15 UTC, dananjohnson commented on public/localeStrings/en/translation.json
> +    "success_message_educator": "Your account has been activated, but it will need to be approved by an administrator before you can access educator content. You will receive an email when you have b
See https://www.i18next.com/translation-function/context

2023-08-11 16:29 UTC, alexgoff commented on public/localeStrings/en/translation.json
> +    "success_message_educator": "Your account has been activated, but it will need to be approved by an administrator before you can access educator content. You will receive an email when you have b
oh, I didn't catch that `pendingGroup` was a variable and not a string, I was looking for a key like "success_message_pendingGroup" 🤯  everything looks good 😓

2023-08-11 16:29 UTC, alexgoff approved these changes

2023-08-11 17:25 UTC, merged