[F] Reference Modal Block
lsst-epo/investigations-client pull request #73
Opened 2023-11-02 17:10 UTC by alexgoff

JIRA: https://jira.lsstcorp.org/browse/EPO-8594

## What this change does ##

Adds support for the Reference Modal entry content block. Includes a significant refactor of modals in the application along with support for a standalone reference entry page. 

## Notes for reviewers ##

Check this branch and the corresponding API branch. 
Include an indication of how detailed a review you want on a 1-10 scale.
- 6

## Testing ##

Test the following
- Reference entries exist as a new section and entry type
- Reference entries accept content blocks as children
- Adding a reference entry to a page shows a button
- Clicking the button opens the reference entry content in a modal (optional: a loader shows while the modal is open but content is not fetched yet)
- When the modal is open the URL is re-written to /[investigation]/reference/[entry slug]
    - should the "reference" be a child of the [investigation] param? They aren't tied to any investigation so they could go at the root as /reference/[entry slug] but I'm not sure if there's any auth implications in there
- When the modal is open, either cmd+left arrow navigates back to the previous URL or "escape" closes the modal. 
- If the page is refreshed with the modal open, or the URL is copied and pasted, the content shows in a new page.

## Checklist ##

If any of the following are true, please check them off
- [ ] This is a breaking change: changes in page data (`/src/data/pages/PAGE.json`) or scientific data (anything in `/static/`) and I will notify Product Marketing when it is in prod and user visible.
- [x] This change impacts several investigations (e.g. the change affects reuseed styles, widgets, pages, QAs, utility methods, etc.)
- [x] This change is isolated to a specific page or Component (i.e. it's a one-off)
- [ ] I don't know what this change does

## Screenshots (optional) ##
### Before:
### After:

2023-11-02 17:18 UTC, alexgoff commented on app/[locale]/[investigation]/@modal/default.tsx
> +export default function Default() {
these `default` pages are needed for parallel routes where routing does not exist at the top level

2023-11-02 17:18 UTC, alexgoff commented on app/[locale]/[investigation]/layout.tsx
> +  modal,
for parallel routes, a named child component is passed as a prop and then rendered alongside `children` whereever we choose it.

2023-11-02 17:18 UTC, alexgoff commented on app/[locale]/[investigation]/reference/[slug]/page.tsx
> +  return <ReferenceContentPage data={entry} site={site} />;
this is the standalone reference page routing

2023-11-02 17:18 UTC, alexgoff commented on app/[locale]/layout.tsx
> +        style={{ "--scrollbar-width": "calc(100vw - 100%)" }}
added this so that non-fullscreen modals can get the width of the screen minus any visible scrollbars

2023-11-02 17:18 UTC, alexgoff commented on components/content-blocks/Modal/index.tsx
rewrote this entire block, the previous setup didn't reflect how this is intended to work.

2023-11-02 17:18 UTC, alexgoff commented on components/factories/ContentBlockFactory/ContentBlockFactory.tsx
> +      hasModal={hasModal}
added these so we can control if content blocks render in their modal-open state, and if they have modal controls (for reference modals we want them "open" but NOT showing their own modal controls or we get duplicate modals)

2023-11-02 17:18 UTC, alexgoff commented on components/hoc/withModal/withModal.tsx
> +    if (!hasModal) {
to escape the `withModal` wrapper on images and widgets, we set `hasModal` to false when rendered inside of a reference modal

2023-11-02 17:18 UTC, alexgoff commented on components/hoc/withModal/withModal.tsx
> +      <Modal.Base
the rest is just following refactor to move modal functionality into a reusable base

2023-11-02 17:18 UTC, alexgoff commented on components/layout/Modal/Base/index.tsx
> +        >
this modal base handles everything up to the dialog container with focus trap and keyboard events

2023-11-02 17:18 UTC, alexgoff commented on components/templates/ReferenceContentPage/index.tsx
> +    <Styled.ContentBlocks paddingSize="none" width="wide" bgColor="transparent">
this is the content that goes either into the reference page or reference modal

2023-11-07 03:26 UTC, blnkt requested changes
Update as needed based on changes to analogous [investigations-api refactor](https://github.com/lsst-epo/investigations-api/pull/42)

2023-11-08 00:22 UTC, merged